#!/usr/bin/env bash
# Ce script écoute sur le port 98 sur localhost et affiche les messages reçus.

# Utilisation de `nc` (netcat) pour écouter sur le port 98
echo "Listening on port 98..."
nc -lk 98
